CREATE TABLE Clientes_Banca
(
    NoCuenta VARCHAR(5),
    Nombre VARCHAR(30),
    Saldo NUMERIC(10,2),

	PRIMARY KEY (NoCuenta)
);

CREATE TABLE Tipos_Movimiento
(
    ClaveM VARCHAR(2),
	Descripcion VARCHAR(30),

	PRIMARY KEY (ClaveM)
);

CREATE TABLE Movimientos
(
	NoCuenta VARCHAR(5),
	ClaveM VARCHAR(2),
    Fecha DATETIME,
	Monto NUMERIC(10,2),

	PRIMARY KEY (NoCuenta, ClaveM, Fecha),
    FOREIGN KEY (NoCuenta) REFERENCES Clientes_Banca (NoCuenta),
    FOREIGN KEY (ClaveM) REFERENCES Tipos_Movimiento (ClaveM)
);
-------------------------------------------
BEGIN TRANSACTION PRUEBA1
INSERT INTO CLIENTES_BANCA VALUES('001', 'Manuel Rios Maldonado', 9000);
INSERT INTO CLIENTES_BANCA VALUES('002', 'Pablo Perez Ortiz', 5000);
INSERT INTO CLIENTES_BANCA VALUES('003', 'Luis Flores Alvarado', 8000);
COMMIT TRANSACTION PRUEBA1

SELECT * FROM CLIENTES_BANCA

BEGIN TRANSACTION PRUEBA2
INSERT INTO CLIENTES_BANCA VALUES('004','Ricardo Rios Maldonado',19000);
INSERT INTO CLIENTES_BANCA VALUES('005','Pablo Ortiz Arana',15000);
INSERT INTO CLIENTES_BANCA VALUES('006','Luis Manuel Alvarado',18000);

SELECT * FROM CLIENTES_BANCA

ROLLBACK TRANSACTION PRUEBA2
---------------------------------------
BEGIN TRANSACTION PRUEBA3
	INSERT INTO TIPOS_MOVIMIENTO VALUES
	('A','Retiro Cajero Automatico'), 
	('B','Deposito Ventanilla');
COMMIT TRANSACTION PRUEBA3


BEGIN TRANSACTION PRUEBA4	
	INSERT INTO MOVIMIENTOS VALUES('001','A',GETDATE(),500);
	UPDATE CLIENTES_BANCA SET SALDO = SALDO -500 WHERE NoCuenta='001'
COMMIT TRANSACTION PRUEBA4

SELECT * FROM CLIENTES_BANCA
SELECT * FROM MOVIMIENTOS

------------------------------------------

BEGIN TRANSACTION PRUEBA5
	INSERT INTO CLIENTES_BANCA VALUES
	('005','Rosa Ruiz Maldonado',9000),
	('006','Luis Camino Ortiz',5000),
	('001','Oscar Perez Alvarado',8000);

	IF @@ERROR = 0
		COMMIT TRANSACTION PRUEBA5
	ELSE
		BEGIN
			PRINT 'A transaction needs to be rolled back'
		ROLLBACK TRANSACTION PRUEBA5
	END

-----------------------------------------

IF EXISTS (SELECT name FROM sysobjects
            WHERE name = 'REGISTRAR_RETIRO_CAJERO' AND type = 'P')
    DROP PROCEDURE REGISTRAR_RETIRO_CAJERO
GO

CREATE PROCEDURE REGISTRAR_RETIRO_CAJERO 
    @NoCuenta  VARCHAR(5),
    @Monto NUMERIC(10,2)
AS
	BEGIN TRANSACTION T1
		INSERT INTO MOVIMIENTOS VALUES(@NoCuenta,'A',GETDATE(),@Monto);
		UPDATE CLIENTES_BANCA SET SALDO = SALDO - @Monto
		WHERE NoCuenta = @NoCuenta
	IF @@ERROR = 0
		COMMIT TRANSACTION T1
	ELSE
		BEGIN
			PRINT 'El retiro se tuvo que cancelar.'
		ROLLBACK TRANSACTION T1
	END
GO



CREATE PROCEDURE REGISTRAR_DEPOSITO_VENTANILLA  
    @NoCuenta  VARCHAR(5),
    @Monto NUMERIC(10,2)
AS
	BEGIN TRANSACTION T2
		UPDATE CLIENTES_BANCA SET SALDO = SALDO + @Monto
		WHERE NoCuenta = @NoCuenta;
		INSERT INTO MOVIMIENTOS VALUES(@NoCuenta,'B',GETDATE(),@Monto)
	IF @@ERROR = 0
		COMMIT TRANSACTION T2
	ELSE
		BEGIN
			PRINT 'El deposito se tuvo que cancelar.'
		ROLLBACK TRANSACTION T2
	END
GO

EXECUTE REGISTRAR_RETIRO_CAJERO '005', 500;
EXECUTE REGISTRAR_DEPOSITO_VENTANILLA '005', 500;

SELECT * FROM CLIENTES_BANCA
SELECT * FROM Tipos_Movimiento
SELECT * FROM Movimientos